set_property PACKAGE_PIN U8 [get_ports pcie_clk_p]
set_property PACKAGE_PIN U7 [get_ports pcie_clk_n]
create_clock -period 10.000 -name pcie_clk [get_ports pcie_clk_p]

set_property PACKAGE_PIN L4 [get_ports pcie_txp[0]]
set_property PACKAGE_PIN L3 [get_ports pcie_txn[0]]
set_property PACKAGE_PIN M6 [get_ports pcie_rxp[0]]
set_property PACKAGE_PIN M5 [get_ports pcie_rxn[0]]
set_property PACKAGE_PIN M2 [get_ports pcie_txp[1]]
set_property PACKAGE_PIN M1 [get_ports pcie_txn[1]]
set_property PACKAGE_PIN P6 [get_ports pcie_rxp[1]]
set_property PACKAGE_PIN P5 [get_ports pcie_rxn[1]]
set_property PACKAGE_PIN N4 [get_ports pcie_txp[2]]
set_property PACKAGE_PIN N3 [get_ports pcie_txn[2]]
set_property PACKAGE_PIN R4 [get_ports pcie_rxp[2]]
set_property PACKAGE_PIN R3 [get_ports pcie_rxn[2]]
set_property PACKAGE_PIN P2 [get_ports pcie_txp[3]]
set_property PACKAGE_PIN P1 [get_ports pcie_txn[3]]
set_property PACKAGE_PIN T6 [get_ports pcie_rxp[3]]
set_property PACKAGE_PIN T5 [get_ports pcie_rxn[3]]
set_property PACKAGE_PIN T2 [get_ports pcie_txp[4]]
set_property PACKAGE_PIN T1 [get_ports pcie_txn[4]]
set_property PACKAGE_PIN V6 [get_ports pcie_rxp[4]]
set_property PACKAGE_PIN V5 [get_ports pcie_rxn[4]]
set_property PACKAGE_PIN U4 [get_ports pcie_txp[5]]
set_property PACKAGE_PIN U3 [get_ports pcie_txn[5]]
set_property PACKAGE_PIN W4 [get_ports pcie_rxp[5]]
set_property PACKAGE_PIN W3 [get_ports pcie_rxn[5]]
set_property PACKAGE_PIN V2 [get_ports pcie_txp[6]]
set_property PACKAGE_PIN V1 [get_ports pcie_txn[6]]
set_property PACKAGE_PIN Y6 [get_ports pcie_rxp[6]]
set_property PACKAGE_PIN Y5 [get_ports pcie_rxn[6]]
set_property PACKAGE_PIN Y2  [get_ports pcie_txp[7]]
set_property PACKAGE_PIN Y1  [get_ports pcie_txn[7]]
set_property PACKAGE_PIN AA4 [get_ports pcie_rxp[7]]
set_property PACKAGE_PIN AA3 [get_ports pcie_rxn[7]]

set_property PACKAGE_PIN G25 [get_ports pcie_perst_ls]
set_property IOSTANDARD LVCMOS25 [get_ports pcie_perst_ls]
set_property PULLUP true [get_ports pcie_perst_ls]
set_false_path -from [get_ports pcie_perst_ls]

#set_property PACKAGE_PIN F23 [get_ports pcie_wake_b_ls]
#set_property IOSTANDARD LVCMOS25 [get_ports pcie_wake_b_ls]

#set_false_path -through [get_pins xdma_i/inst/pcie3_ip_i/inst/pcie_top_i/pcie_7vx_i/PCIE_3_0_i/CFGMAX*]
#set_false_path -through [get_nets xdma_i/inst/cfg_max*]

set_property LOC IBUFDS_GTE2_X0Y1 [get_cells i_refclk_ibuf]
